<?php

/**
 * @file
 * This module provides an extra link in the Drupal menu that links to
 * an external help site. For example, it might be configured to link to a
 * Drupal service provider's knowledgebase.
 *
 * @author Christopher Torgalson <chris@raisedeyebrow.com>
 */


// Constants (default admin settings form values):
define('RE_HELP_URL', 'http://drupal.org/user');
define('RE_HELP_DESTINATION', NULL);
define('RE_HELP_HTTP_RESPONSE_CODE', 302);
define('RE_HELP_MENU_LINK_TEXT', 'RE Help Manual');


/**
 * This function handles the redirect when the admin/help/re_help link is
 * clicked.
 *
 * @param array $options Array containing three items:
 *                          -- (string) url: the url to redirect to
 *                          -- (string) destination: the query string for the url
 *                             (will be urlencoded and appended as ?destination=foo
 *                          -- (int) http_response_code: 302 by default
 */
function _re_help_redirect($options) {
  drupal_goto($options['url'], !empty($options['destination']) ? 'destination='. urlencode($options['destination']) : NULL, NULL, $options['http_response_code']);
} // _re_help_redirect()


/**
 * Provides admin settings form.
 */
function re_help_admin_settings() {
  // Warning to admins:
  drupal_set_message(t('<strong>Notice</strong>: flush the menu cache or visit the !menu-page after making changes to this form.', array('!menu-page' => l(t('menu settings page'), 'admin/build/menu', array('html' => TRUE)))), 'warning', FALSE);
  // We need a form array:
  $form = array();
  // Help url field:
  $form['re_help_url'] = array(
    '#title' => t('Help Site URL'),
    '#description' => t('The URL to redirect to. Defaults to the user page of the help site.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('re_help_url', RE_HELP_URL),
    '#weight' => -15,
  );
  // Help destination field:
  $form['re_help_destination'] = array(
    '#title' => t('Link Destination'),
    '#description' => t('The destination for the user if, as in the default case, the Help Site URL is set to a login page.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('re_help_destination', RE_HELP_DESTINATION),
    '#weight' => -10,
  );
  // HTTP response code field:
  $form['re_help_http_response_code'] = array(
    '#title' => t('HTTP Response Code'),
    '#description' => t('HTTP response code for the redirect from <em>this</em> site to the help site. Set to 302 by default and should seldom need alteration.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('re_help_http_response_code', RE_HELP_HTTP_RESPONSE_CODE),
    '#weight' => -5,
  );
  $form['re_help_menu_link_text'] = array(
    '#title' => t('Menu Item Help Text'),
    '#description' => t('This is the text that will appear in the help menu link.'),
    '#type' => 'textfield',
    '#default_value' => variable_get('re_help_menu_link_text', RE_HELP_MENU_LINK_TEXT),
    '#weight' => 0,
  );
  // Return the completed form:
  return system_settings_form($form);
} // re_help_admin_settings()


/**
 * Implementation of hook_menu().
 */
function re_help_menu() {
  $items = array();
  // Menu item for the settings page:
  $items['admin/settings/re_help'] = array(
    'title' => 'RE Help Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('re_help_admin_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  // The help menu item itself:
  $items['admin/help/re_help'] = array(
    'title' => variable_get('re_help_menu_link_text', RE_HELP_MENU_LINK_TEXT),
    'page callback' => '_re_help_redirect',
    'page arguments' => array(
      array(
        'url' => variable_get('re_help_url', RE_HELP_URL),
        'destination' => variable_get('re_help_destination', RE_HELP_DESTINATION),
        'http_response_code' => variable_get('re_help_http_response_code', RE_HELP_HTTP_RESPONSE_CODE),
      ),
    ),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  // Return the array:
  return $items;
} // re_help_menu()